### ISSUE TITLE
Bug? Cannot print "Hello world!" in python

### ISSUE THREAD

**Issue by fexcode** [BaiChuanByte/HelloWorld#1]
在python3.12中, 运行更改后缀后的 any.py 文件,无输出

猜测:
 import __hello__ 并不会输出,因为没有调用输出的函数

**Comment by fexcode** [comment]
python有一个issue也讲到了这个问题
https://github.com/python/cpython/issues/100136#issuecomment-1344428244

**Comment by BaiChuanByte** [comment]
Please remove the .gitignore...

**Comment by BaiChuanByte** [comment]
And please use the English

**Comment by fexcode** [comment]
<the English>

**Comment by fexcode** [comment]
"the English"

**Comment by fexcode** [comment]
Please agree to my PR.
